template_type: NOQ::Core::Config
version: '1'
aws:
  accounts:
    - account_id: '192455039954'
      account_name: iambic_test_spoke_account_2
      iambic_managed: read_and_write
      org_id: o-8t0mt0ybdd
      spoke_role_arn: arn:aws:iam::192455039954:role/IambicSpokeRole
    - account_id: '333972133479'
      account_name: iambic_test_spoke_account_3
      iambic_managed: read_and_write
      org_id: o-8t0mt0ybdd
      spoke_role_arn: arn:aws:iam::333972133479:role/IambicSpokeRole
    - account_id: '442632209887'
      account_name: iambic_test_spoke_account_1
      iambic_managed: read_and_write
      org_id: o-8t0mt0ybdd
      spoke_role_arn: arn:aws:iam::442632209887:role/IambicSpokeRole
    - account_id: '580605962305'
      account_name: iambic_test_org_account
      iambic_managed: read_and_write
      org_id: o-8t0mt0ybdd
      spoke_role_arn: arn:aws:iam::580605962305:role/IambicSpokeRole
  organizations:
    - aws_profile: iambic_test_org_account/iambic_test_org_account_admin
      default_rule:
        iambic_managed: read_and_write
      hub_role_arn: arn:aws:iam::580605962305:role/IambicHubRole
      identity_center:
        region: us-east-1
      org_account_id: '580605962305'
      org_id: o-8t0mt0ybdd
extends:
  - assume_role_arn: arn:aws:iam::580605962305:role/IambicSpokeRole
    key: AWS_SECRETS_MANAGER
    value: arn:aws:secretsmanager:us-east-1:580605962305:secret:iambic-config-secrets-c03d249e-a067-461c-a6a4-7d7d97f40bda-Bpuwi1
