template_type: NOQ::Okta::App
template_schema_url: https://docs.iambic.org/reference/schemas/okta_app_template
idp_name: development
properties:
  name: test_application
  id: 0oa8v74v2b9mCTGSl5d7
  status: ACTIVE
